name = "posthog-reverse-proxy"
main = "src/index.js"
compatibility_date = "2024-06-01"

[observability.logs]
enabled = false

[env.production]
name = "posthog-reverse-proxy-prod"

[env.staging]
name = "posthog-reverse-proxy-staging"